language: python
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- nightly
env:
  global:
    - VENV_ARGS="--system-site-packages"
install:
- pip install -U pip setuptools
- pip install .
- pip install PyYAML
- pip install coverage
- pip install coveralls
script:
- coverage run --source=exchangelib setup.py test
after_success: coveralls
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python-lxml python3-lxml
- openssl aes-256-cbc -K $encrypted_e7f042a9cf96_key -iv $encrypted_e7f042a9cf96_iv
  -in settings.yml.enc -out settings.yml -d
