language: python
python:
- '3.4'
- '3.5'
- 3.6-dev
- nightly
install:
- python setup.py install
- pip install PyYAML
- pip install coverage
- pip install coveralls
script:
- coverage run --source=exchangelib setup.py test
after_success: coveralls
